- name: Add public IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ item }} {{ hostvars[item].ansible_hostname }}"
    state: present
  when: (hostvars[item].ansible_hostname is defined) and
        (ansible_virtualization_type != 'docker') and
        (not rabbitmq_use_internal_ip|bool)
  with_items: "{{ groups[rabbitmq_group] }}"

- name: Add private IP address of all hosts to all hosts
  lineinfile:
    dest: /etc/hosts
    regexp: '.*{{ item }}$'
    line: "{{ hostvars[item]['ansible_default_ipv4']['address'] }} {{ hostvars[item].ansible_hostname }}"
    state: present
  when: (hostvars[item].ansible_hostname is defined) and
        (ansible_virtualization_type != 'docker') and
        (rabbitmq_use_internal_ip|bool)
  with_items: "{{ groups[rabbitmq_group] }}"

- name: Include rabbitmq_packages_centos.yml
  include_tasks: rabbitmq_packages_centos.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: rabbitmq_packages_ubuntu.yml
  when: ansible_os_family == 'Debian'

# Install RabbitMQ Plugins
- name: Include rabbitmq_plugins.yml
  include_tasks: rabbitmq_plugins.yml

- name: Include rabbitmq_tls_self_signed.yml
  include_tasks: rabbitmq_tls_self_signed.yml
  when: rabbitmq_tls_generate_self_signed_cert

- name: Include rabbitmq_install_custom_cert.yml
  include_tasks: rabbitmq_install_custom_cert.yml
  when: rabbitmq_tls_use_custom_cert

# TLS tasks
- name: Include rabbitmq_tls.yml
  include_tasks: rabbitmq_tls.yml
  when: rabbitmq_tls_enable

- name: Run Cluster Tasks for EC2 cluster
  include_tasks: rabbitmq_ec2_cluster.yml
  when: rabbitmq_clustering_type == "ec2"

# Start and enable rabbitmq service
- name: Include rabbitmq_service.yml
  include_tasks: rabbitmq_service.yml

- name: Run Cluster Tasks for static cluster
  block:
    - name: Set master name as first host in inventory
      set_fact:
        master_node: "{{ groups[rabbitmq_group][0] }}"

    - name: Include rabbitmq_clustering_centos.yml
      include_tasks: rabbitmq_clustering_centos.yml
  when: (groups[rabbitmq_group] | length > 1) and
        (rabbitmq_clustering_type == "static")

# Setup user and vhost
- include_tasks: rabbitmq_user.yml

# Setup HA policy
- include_tasks: rabbitmq_ha_config.yml

# Setup Queue policy
- include_tasks: rabbitmq_queue_policy.yml